name: Build, Push and Deploy Docker Images

on: push

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures the entire repo history is checked out

      - name: Set up Docker Builder
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: rajinikanthvadla
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image for each service
        run: |
          for dir in src/*/ ; do
            if [ -f "$dir/Dockerfile" ]; then
              service_dir=${dir%*/}  # Strip the trailing /
              service_name=${service_dir##*/}  # Extract the directory name
              echo "Building Docker image for $service_name"
              
              # Navigate into the service directory
              cd $service_dir
              
              # Debug: List files in the current service directory
              echo "Listing contents of $service_dir:"
              ls -alh

              # Define the image tag
              image_tag="v1$(git rev-list --count HEAD)-$service_name"
              
              # Build the Docker image
              echo "Building Docker image with tag $image_tag"
              docker build -t rajinikanthvadla/dockerchappie:$image_tag .
              
              # Push the Docker image
              echo "Pushing Docker image to registry"
              docker push rajinikanthvadla/dockerchappie:$image_tag
              
              # Return to the root directory
              cd ../../
            fi
          done

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Configure Kubernetes
        run: |
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Update Kubernetes manifest in EKS
        run: |
          for dir in src/*/; do
            if [ -f "$dir/Dockerfile" ]; then
              service_name=$(basename "$dir")
              image_tag="v1$(git rev-list --count HEAD)-$service_name"
              k8s_files=$(find ./kubernetes-manifests -type f -name "*.yaml" -o -name "*.yml")
              for file in $k8s_files; do
                sed -i "s|rajinikanthvadla/dockerchappie:.*|$service_name rajinikanthvadla/dockerchappie:$image_tag|g" $file
                kubectl apply -f $file --validate=false
              done
            fi
          done

      - name: Commit and push updates
        run: |
          git config --local user.email "rajinikanthvadla9@github.com"
          git config --local user.name "rajinikanthvadla"
          git diff --quiet && git diff --staged --quiet || (git commit -am "Update Kubernetes manifests with new image tags [skip ci]" && git push)
        env:
          GIT_COMMITTER_NAME: rajinikanthvadla
          GIT_COMMITTER_EMAIL: rajinikanthvadla9@github.com
