name: Build, Push and Deploy Docker Images

on: push

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures the entire repo history is checked out

      - name: List files in the repo root
        run: ls -alh

      - name: Set up Docker Builder
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: rajinikanthvadla
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image for each service
        run: |
          for dir in src/*/; do
            if [ -f "$dir/Dockerfile" ]; then
              # Navigate into the service directory
              cd $dir
              
              # Extract the name of the service based on the directory name
              service_name=$(basename "$dir")

              # Debug: List files in the current service directory
              echo "Listing contents of $service_name:"
              ls -alh
              
              # Define the image tag
              image_tag="v1$(git rev-list --count HEAD)-$service_name"
              
              # Build and push the Docker image
              echo "Building Docker image for $service_name with tag $image_tag"
              docker build -t rajinikanthvadla/dockerchappie:$image_tag -f Dockerfile .
              docker push rajinikanthvadla/dockerchappie:$image_tag
              
              # Navigate back to the root directory
              cd -
            fi
          done

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update Kubernetes manifest in EKS
        run: |
          for dir in src/*/; do
            if [ -f "$dir/Dockerfile" ]; then
              # Extract the name of the service based on the directory name
              service_name=$(basename "$dir")

              # Find and update Kubernetes manifests
              k8s_files=$(find ./kubernetes-manifests -type f -name "*.yaml" -o -name "*.yml")
              for file in $k8s_files; do
                sed -i "s|rajinikanthvadla/dockerchappie:.*|$service_name rajinikanthvadla/dockerchappie:$image_tag|g" $file
              done

              # Apply the Kubernetes manifests
              kubectl apply -f ./kubernetes-manifests/
            fi
          done

      - name: Commit and push updates
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update Kubernetes manifests with new image tags [skip ci]"
          git push
