name: Build, Push and Deploy Docker Images

on: push

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures the entire repo history is checked out

      - name: List files
        run: ls -alh  # Lists all files and directories in the current directory

      - name: Set up Docker Builder
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: rajinikanthvadla
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image for each service
        run: |
          for dir in src/*/ ; do
            if [ -f "$dir/Dockerfile" ]; then
              service_dir=${dir%*/}  # Strip the trailing /
              service_name=${service_dir##*/}  # Extract the directory name
              echo "Building Docker image for $service_name in $service_dir"
              docker build -t rajinikanthvadla/dockerchappie:${{ github.sha }}-$service_name -f $dir/Dockerfile .
              docker push rajinikanthvadla/dockerchappie:${{ github.sha }}-$service_name
            fi
          done

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update Kubernetes manifest in EKS
        run: |
          for dir in src/*/ ; do
            if [ -f "$dir/Dockerfile" ]; then
              service_dir=${dir%*/}  # Strip the trailing /
              service_name=${service_dir##*/}  # Extract the directory name
              k8s_files=$(find kubernetes-manifests -type f -name "*.yaml" -o -name "*.yml")
              for file in $k8s_files; do
                kubectl set image -f $file serviceName=$service_name rajinikanthvadla/dockerchappie:${{ github.sha }}-$service_name --record
              done
              kubectl apply -f kubernetes-manifests/
            fi
          done

      - name: Commit and push updates
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update Kubernetes manifests with new image tags [skip ci]"
          git push
